[Streamers]
bonniecruz

[General]
SITE_TMPL = https://chaturbate.com/{username}       # URL where the live stream can be accessed. {username} will be replaced with the streamer's username.
CHECK_INTERVAL = 60                                 # How often to check if streamers are live (in seconds).  (Default: 60)
OUTPUT_DIR = "G:\share\recordings"                  # Folder where recordings will be saved.
OUTPUT_TMPL = "%(title)s.%(ext)s"                   # Template for naming the files. (Reference: https://github.com/yt-dlp/yt-dlp#output-templates)
YT_DLP_PATH =                                       # Full path to the yt-dlp executable.  Can be left blank if yt-dlp is in the system's PATH.
LOGGING = false                                     # Log yt-dlp and ffmpeg output to a file.
SPLIT_LOGS = true                                   # When LOGGING = true, create 2 separate log files.  One for yt-dlp (stdout) and one for ffmpeg (stderr). 
LOG_PATH =                                          # Path to the log file.  Can be left blank to use the current directory.
STALL_CHECK_INTERVAL = 30                           # How often to check if a stream is stalling (in seconds). (Default: 30)
STALL_TIMEOUT = 120                                 # Time to wait before considering a stream stalled (in seconds). (Default: 120)
CONFIG_CHECK_INTERVAL = 3                           # How often to check for changes to the configuration file (in seconds). (Default: 3)


[Checker]
--dump-json


[Downloader]
--fixup never
--no-part


[Block]
