[Streamers]
celebi_cos
emiru247
ksdhfuksd
jjghfgh

[General]
CHECK_INTERVAL = 60
OUTPUT_DIR = "G:\share\debug\recordings"
OUTPUT_TMPL = "%(title)s [%(id)s].%(ext)s"
COOLDOWN_AFTER_RECORDING = 5
YT_DLP_PATH = C:\Program Files\yt-dlp\yt-dlp.exe
LOGGING = true
LOG_PATH = G:\share\debug.log
SITE_TMPL = https://twitch.tv/{username}
STALL_CHECK_INTERVAL = 10
STALL_TIMEOUT = 45


[Checker]
--dump-json


[Downloader]
--cookies-from-browser firefox
--fixup never
--no-part


[Block]
hachubby