[Streamers]
emiru
ashisbees

[General]
# URL where the live stream can be accessed. {username} will be replaced with the streamer's username.
SITE_TMPL = https://tiktok.com/@{username}/live             

# How often to check if streamers are live (in seconds).  (Default: 60)
CHECK_INTERVAL = 60                                         

# Folder where recordings will be saved.  Can be an absolute path or relative path.  example: "C:\recordings" or "recordings"
OUTPUT_DIR = recordings                                     

# Template for naming the files. (Reference: https://github.com/yt-dlp/yt-dlp#output-templates)
OUTPUT_TMPL = "%(uploader)s %(title)s [%(id)s].%(ext)s"     

# Full path to the yt-dlp executable.  Can be left blank if yt-dlp is in the system's PATH.
# bin/yt-dlp.exe is a forked version that fixes the live checker. 
YT_DLP_PATH = bin/yt-dlp.exe

# Log yt-dlp and ffmpeg output to a file.
LOGGING = false                                             

# When LOGGING = true, create 2 separate log files.  One for yt-dlp (stdout) and one for ffmpeg (stderr). 
SPLIT_LOGS = true                                           

# Path to save the log file.  Can be an absolute or relative path.
LOG_PATH = logs/tiktok-live.log                                             

# How often to check if the file has stalled (in seconds). (Default: 30)
STALL_CHECK_INTERVAL = 30                                   

# Time to wait before considering a file stalled (in seconds). (Default: 120)
STALL_TIMEOUT = 120                                         

# How often to check for changes to the configuration file (in seconds). (Default: 3)
CONFIG_CHECK_INTERVAL = 3                                   

# Log debug messages to a file.
DEBUG_LOGS = false

# Path to save the debug log file.  Can be an absolute or relative path.
DEBUG_LOG_PATH = logs/tiktok-live_debug.log

# Show a popup notification when a streamer goes live.
POPUP_NOTIFICATIONS = true

# Time to show the popup notification (in seconds).
POPUP_TIMEOUT = 15

[Checker]
--cookies-from-browser
firefox
--dump-json


[Downloader]
--fixup never
--no-part
-f flv-origin


[Block]
