[Streamers]
bonniecruz

[General]
# The name of this site
SITE_LABEL = chaturbate

# The position on the dashboard to display this site's panel (e.g. 0 for top-left, 1 for top-right, 2 for bottom-left, 3 for bottom-right, etc.)
SITE_ORDER = 2

# When true, site panels will expand vertically as needed to display all streamers.
PANEL_RESIZE = true

# When recording a stream, split the video file(s) every X minutes. (0 = no split)
SPLIT_AFTER = 0

# URL where the live stream can be accessed. {username} will be replaced with the streamer's username.
SITE_TMPL = https://chaturbate.com/{username}               

# How often to check if streamers are live (in seconds).  (Default: 60)
CHECK_INTERVAL = 60                                         

# Seconds to wait after a recording ends before checking again.
COOLDOWN_AFTER_RECORDING = 60

# Folder where recordings will be saved.  Can be an absolute path or relative path.  example: "C:\recordings" or "recordings"
OUTPUT_DIR = recordings

# Template for naming the video files. (Reference: https://github.com/yt-dlp/yt-dlp#output-templates)
OUTPUT_TMPL = "%(title)s.%(ext)s"

# Highlight the "Last Live" timestamp when the streamer was last live within X days.
LAST_LIVE_HIGHLIGHT = 1

# Path to the yt-dlp executable.  "YT_DLP_PATH = bin/yt-dlp.exe" to use the bundled windows executable.  "YT_DLP_PATH = bin/yt-dlp" to use the bundled linux executable.  "YT_DLP_PATH = yt-dlp" to use PATH
YT_DLP_PATH_WINDOWS = bin/yt-dlp.exe
# Path to the yt-dlp executable.  "YT_DLP_PATH = bin/yt-dlp.exe" to use the bundled windows executable.  "YT_DLP_PATH = bin/yt-dlp" to use the bundled linux executable.  "YT_DLP_PATH = yt-dlp" to use PATH
YT_DLP_PATH_MAC = 
# Path to the yt-dlp executable.  "YT_DLP_PATH = bin/yt-dlp.exe" to use the bundled windows executable.  "YT_DLP_PATH = bin/yt-dlp" to use the bundled linux executable.  "YT_DLP_PATH = yt-dlp" to use PATH
YT_DLP_PATH_LINUX = bin/yt-dlp

# Log yt-dlp (stdout) and ffmpeg (stderr) to a file.
LOGGING = false

# When LOGGING = true, create 2 separate log files.  One for yt-dlp (stdout) and one for ffmpeg (stderr).
SPLIT_LOGS = true

# Path to save the log file.  Can be an absolute or relative path.
LOG_PATH = logs/chaturbate.log

# How often to check if the recording has stalled (in seconds). (Default: 30)
STALL_CHECK_INTERVAL = 30                                   

# Time to wait before considering a recording stalled (in seconds). (Default: 120)
STALL_TIMEOUT = 120                                         

# How often to check for changes to the configuration file (in seconds). (Default: 3)
CONFIG_CHECK_INTERVAL = 3                                   

# Show a popup notification when a streamer goes live.
POPUP_NOTIFICATIONS = true

# Seconds to show the popup notification when a streamer goes live.
POPUP_TIMEOUT = 15

# Push a notification to your phone via ntfy.sh when a recording starts. This requires NTFY_TOPIC to be set in the GLOBAL SETTINGS panel. (true/false)
NTFY_NOTIFICATIONS = true

# Duration of the progress bar in the site panel of the dashboard. (in hours)
PROGRESS_BAR_MAX_HOURS = 10

# Width of the progress bar in the site panel of the dashboard. (in characters)
PROGRESS_BAR_WIDTH = 58

# Whether to write the --cookies-from-browser flag to this config file's [Downloader] section when a browser is selected at startup.
DOWNLOADER_COOKIES = False

# Whether to write the --cookies-from-browser flag to this config file's [Checker] section when a browser is selected at startup.
CHECKER_COOKIES = False

# Show an alert in the system panel when ads are detected in a recording (true/false).
AD_ALERTS = false

# Restart the recording when a higher quality is available. (true/false).
QUALITY_UPGRADE = true

[Checker]
--dump-json


[Downloader]
--fixup never
--no-part
--downloader-args ffmpeg:"-fps_mode passthrough -copyts -avoid_negative_ts make_zero"


[LQ_Downloader]
-f
4
--fixup never
--no-part


[Block]
