[Streamers]
bonniecruz


[General]
# The name of this site
SITE_LABEL = chaturbate

# The position on the dashboard to display this site's panel (e.g. 0 for top-left, 1 for top-right, 2 for bottom-left, 3 for bottom-right, etc.)
SITE_ORDER = 2

# When recording a stream, split the video file(s) every X minutes. (0 = no split)
SPLIT_AFTER = 0

# URL where the live stream can be accessed. {username} will be replaced with the streamer's username.
SITE_TMPL = https://chaturbate.com/{username}               

# How often to check if streamers are live (in seconds).  (Default: 60)
CHECK_INTERVAL = 60                                         

# Folder where recordings will be saved.  Can be an absolute path or relative path.  example: "C:\recordings" or "recordings"
OUTPUT_DIR = recordings                                     

# Template for naming the video files. (Reference: https://github.com/yt-dlp/yt-dlp#output-templates)
OUTPUT_TMPL = "%(title)s.%(ext)s"                           

# Highlight the "Last Live" timestamp when the streamer was last live withing X days.
LAST_LIVE_HIGHLIGHT = 1

# Full path to the yt-dlp executable.  Can be left blank if yt-dlp is in the system's PATH. (Default: bin/yt-dlp.exe)
YT_DLP_PATH = bin/yt-dlp.exe

# Show the remaining disk space for these drives in the system panel.  Leave blank to use the current drive.  Example: C:\, D:\, G:\
DISK_DRIVES = 

# Log yt-dlp (stdout) and ffmpeg (stderr) to a file.
LOGGING = false                                             

# When LOGGING = true, create 2 separate log files.  One for yt-dlp (stdout) and one for ffmpeg (stderr). 
SPLIT_LOGS = true                                           

# Path to save the log file.  Can be an absolute or relative path.
LOG_PATH = logs/chaturbate.log                                             

# How often to check if the recording has stalled (in seconds). (Default: 30)
STALL_CHECK_INTERVAL = 30                                   

# Time to wait before considering a recording stalled (in seconds). (Default: 120)
STALL_TIMEOUT = 120                                         

# How often to check for changes to the configuration file (in seconds). (Default: 3)
CONFIG_CHECK_INTERVAL = 3                                   

# Log debug messages to a file.
DEBUG_LOGS = false

# Path to save the debug log file.  Can be an absolute or relative path.
DEBUG_LOG_PATH = logs/chaturbate_debug.log

# Show a popup notification when a streamer goes live.
POPUP_NOTIFICATIONS = true

# Seconds to show the popup notification when a streamer goes live.
POPUP_TIMEOUT = 15

# Minutes to wait before showing another popup notification for the same streamer.
POPUP_COOLDOWN = 30   

# Duration of the progress bar in the site panel of the dashboard. (in hours)
PROGRESS_BAR_MAX_HOURS = 10

# Width of the progress bar in the site panel of the dashboard. (in characters)
PROGRESS_BAR_WIDTH = 58   

# Enables or disables the browser selection at startup. Note: If any config file has this set to True, you will be prompted to choose a browser on startup.
ASK_FOR_BROWSER = False

# Whether to write the --cookies-from-browser flag to this config file when a browser is selected at startup.
SET_COOKIE_FLAG = False

[Checker]
--dump-json


[Downloader]
--fixup never
--no-part


[Block]
