[Streamers]
bonniebruise

[General]
# Config key comments/descriptions now live exclusively in the Config tab of jj-dlp
SITE_LABEL = chaturbate
SITE_ORDER = 2
PANEL_RESIZE = true
SPLIT_AFTER = 0
SITE_TMPL = https://chaturbate.com/{username}               
CHECK_INTERVAL = 60                                         
COOLDOWN_AFTER_RECORDING = 60
OUTPUT_DIR = recordings
OUTPUT_TMPL = "%(title)s.%(ext)s"
LAST_LIVE_HIGHLIGHT = 1
YT_DLP_PATH_WINDOWS = bin\windows\yt-dlp\yt-dlp.exe
YT_DLP_PATH_MAC = yt-dlp
YT_DLP_PATH_LINUX = bin/linux/yt-dlp/yt-dlp
LOGGING = false
SPLIT_LOGS = true
LOG_PATH = 
STALL_CHECK_INTERVAL = 30                                   
STALL_TIMEOUT = 120                                         
CONFIG_CHECK_INTERVAL = 3                                   
POPUP_NOTIFICATIONS = true
POPUP_TIMEOUT = 15
POPUP_COOLDOWN = 240
NTFY_NOTIFICATIONS = true
PROGRESS_BAR_MAX_HOURS = 10
PROGRESS_BAR_WIDTH = 58
AD_ALERTS = false
UPGRADE_QUALITY = true
AUTO_SUFFIX = true

[Checker]
DUMP_JSON = true

[Downloader]
FIXUP = never
NO_PART = true
DOWNLOADER_ARGS = ffmpeg:"-fps_mode passthrough -copyts -avoid_negative_ts make_zero"

[LQ_Downloader]
FORMAT = 4
FIXUP = never
NO_PART = true

[Block]
