[General]

# Comma-separated list of drives or paths to show disk info in the system panel.
# (e.g. C:\\,D:\\  or  /home,/mnt/data).
DISK_DRIVES = 

# Enable debug logging to a file(true/false).
DEBUG_LOGS = false

# Path for the debug log file. Can be a relative or absolute path (e.g. logs/debug.log)
DEBUG_LOG_PATH = logs/debug.log

# Whether to periodically check for app updates (true/false)."
CHECK_FOR_UPDATES = true

# Number of minutes between app update checks.
UPDATE_INTERVAL = 30

# Show the browser chooser on startup (true/false).
ASK_FOR_BROWSER = true

# Show the config file chooser on startup (true/false).
ASK_FOR_CONFIG = true

# Which branch of jj-dlp to update to. (main, testing, or experimental).
UPDATE_BRANCH = main

# Maximum number of simultaneous recordings allowed. (0=no limit)
MAX_CONCURRENT_REC = 0

[Streamers]

[Block]
