[General]

# Comma-separated list of drives or paths to show disk info in the system panel.
# Comma-separated list of drives or paths to show disk info in the system panel. (e.g. C:\, D:\, E:\  or  /home,/mnt/data).
DISK_DRIVES = 

# Enable debug logging to a file(true/false).
DEBUG_LOGS = false

# Path for the debug log file. Can be a relative or absolute path (e.g. logs/debug.log)
DEBUG_LOG_PATH = logs/debug.log

# Whether to check for app updates at startup and periodically (true/false).
CHECK_FOR_UPDATES = true

# Number of minutes between app update checks.
UPDATE_INTERVAL = 30

# Which branch of jj-dlp to update to. (main, testing, or experimental).
UPDATE_BRANCH = main

# Show the browser chooser on startup (true/false).
ASK_FOR_BROWSER = true

# Show the config file chooser on startup (true/false).
ASK_FOR_CONFIG = true

# The maximum number of simultaneous recordings allowed to run.  Use the "PRIORITIES" panel in the Config tab to adjust the priority of each streamer. (0=no limit)
MAX_CONCURRENT_REC = 0

# Order to display streamers on each site panel.   This can also be adjusted by pressing the S key on the Dashboard tab.
SITE_SORT = last_live_desc

# When any recording reaches the ffmpeg error threshold (FF_ERR_THRESH) lower the video qualtiy of the lowest priority streamer, freeing up bandwidth for the remaining streamers.
LQ_DOWNLOADER = false

# Restart the download if we see this many ffmpeg errors ("timestamp discontinuity", "Packet corrupt") default: 200
FF_ERR_THRESH = 200

# Save recordings into a subfolder named after the streamer inside OUTPUT_DIR (true/false).
SUBFOLDERS = false

# The topic name to use for ntfy.sh notifications. (example: jj-dlp-fj48dh734fk) Refer to docs/ntfy-setup.md for a detailed setup guide. (blank = disabled)
NTFY_TOPIC = 

# The URL of the ntfy instance (default: https://ntfy.sh).
NTFY_URL = https://ntfy.sh



[Streamers]

[Block]
