[Streamers]
emiru
ashisbees

[General]
# Config key comments/descriptions now live exclusively in the Config tab of jj-dlp
SITE_LABEL = tiktok-live
SITE_ORDER = 1
PANEL_RESIZE = true
SPLIT_AFTER = 0
SITE_TMPL = https://tiktok.com/@{username}/live             
CHECK_INTERVAL = 60                                         
COOLDOWN_AFTER_RECORDING = 60
OUTPUT_DIR = recordings
OUTPUT_TMPL = "%(uploader)s %(epoch>%Y-%m-%d %H_%M_%S)s.%(ext)s"
LAST_LIVE_HIGHLIGHT = 1
YT_DLP_PATH_WINDOWS = bin\windows\yt-dlp\yt-dlp.exe
YT_DLP_PATH_MAC = yt-dlp
YT_DLP_PATH_LINUX = bin/linux/yt-dlp/yt-dlp
LOGGING = false
SPLIT_LOGS = true
LOG_PATH = 
STALL_CHECK_INTERVAL = 30                                   
STALL_TIMEOUT = 180                                         
CONFIG_CHECK_INTERVAL = 3                                   
POPUP_NOTIFICATIONS = true
POPUP_TIMEOUT = 15
POPUP_COOLDOWN = 30
NTFY_NOTIFICATIONS = true
PROGRESS_BAR_MAX_HOURS = 10
PROGRESS_BAR_WIDTH = 58
DOWNLOADER_COOKIES = True
CHECKER_COOKIES = True
AD_ALERTS = false
UPGRADE_QUALITY = false
AUTO_SUFFIX = true

[Checker]
--cookies-from-browser
firefox
--dump-json


[Downloader]
--cookies-from-browser
firefox


[Block]
