[Streamers]
emiru
eggfok

[General]
# Config key comments/descriptions now live exclusively in the Config tab of jj-dlp
SITE_LABEL = twitch
SITE_ORDER = 0
PANEL_RESIZE = true
SPLIT_AFTER = 0
SITE_TMPL = https://twitch.tv/{username}
CHECK_INTERVAL = 60                                         
COOLDOWN_AFTER_RECORDING = 60
OUTPUT_DIR = recordings
OUTPUT_TMPL = "%(title)s [%(id)s].%(ext)s"
LAST_LIVE_HIGHLIGHT = 1
YT_DLP_PATH_WINDOWS = bin\windows\yt-dlp\yt-dlp.exe
YT_DLP_PATH_MAC = yt-dlp
YT_DLP_PATH_LINUX = bin/linux/yt-dlp/yt-dlp
LOGGING = false
SPLIT_LOGS = true
LOG_PATH = 
STALL_CHECK_INTERVAL = 30
STALL_TIMEOUT = 120
CONFIG_CHECK_INTERVAL = 3
POPUP_NOTIFICATIONS = true
POPUP_TIMEOUT = 15
POPUP_COOLDOWN = 30
NTFY_NOTIFICATIONS = true
PROGRESS_BAR_MAX_HOURS = 10
PROGRESS_BAR_WIDTH = 58
BROWSER = firefox
AD_ALERTS = true
UPGRADE_QUALITY = true
AUTO_SUFFIX = true

[Checker]
COOKIES_FROM_BROWSER = true
DUMP_JSON = true

[Downloader]
VERBOSE = true
COOKIES_FROM_BROWSER = true
FIXUP = never
NO_PART = true

[LQ_Downloader]
FORMAT = 720p60
COOKIES_FROM_BROWSER = true
FIXUP = never
NO_PART = true

[Block]
